---
title: "Untitled"
author: "Yingjie"
date: "`r Sys.Date()`"
output: html_document
---


# Create search 

```{r include=FALSE}
# To clear your environment
remove(list = ls())

Sys.setenv(LANG = "en")

## Load directories
# knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
getwd()

source("./code/_pkgs_dirs.R")
library(googlesheets4)
```


## WOS - done

```{r}
getwd()
### Use data from Google Doc
link <- 'https://docs.google.com/spreadsheets/d/11oUNNjsmzC4wvYwcE8Zm_qavww0D6Twxl8UoPve1WOE/edit?usp=sharing'
wos <- googlesheets4::read_sheet(link, sheet = 'search_wos') %>%
  # dplyr::select(id, model_id, everything()) %>%
  as.data.frame()

names(wos)

Urban <- wos %>% 
  select(Urban) %>%
  filter(!is.na(Urban))

GS <- wos %>% 
  select(GS) %>%
  filter(!is.na(GS))

BS <- wos %>% 
  select(BS) %>%
  filter(!is.na(BS))


MH <- wos %>% 
  select(MH) %>%
  filter(!is.na(MH))


MH_NOT <- wos %>% 
  select(MH_NOT) %>%
  filter(!is.na(MH_NOT))


key_wos_blue <- paste0(
  ## Urban
  '(', paste(Urban$Urban, collapse = ' OR '), ') AND ',
  ## Nature
  '(', paste(BS$BS, collapse = ' OR '), ') AND ',
  
  ## Health
  '(', paste(MH$MH, collapse = ' OR '), ') NOT ',
  
  ## Health
  '(', paste(MH_NOT$MH_NOT, collapse = ' OR '), ')'
  
  )


key_wos_green <- paste0(
  ## Urban
  '(', paste(Urban$Urban, collapse = ' OR '), ') AND ',
  ## Nature
  '(', paste(GS$GS, collapse = ' OR '), ') AND ',
  
  ## Health
  '(', paste(MH$MH, collapse = ' OR '), ') NOT ',
  
  ## Health
  '(', paste(MH_NOT$MH_NOT, collapse = ' OR '), ')'
  
  )


paste0('(', paste(BS$BS, collapse = ' OR '), ')')
paste0('(', paste(GS$GS, collapse = ' OR '), ')')
```


## Scopus
```{r}
wos_scopus <- wos %>%
  mutate(mh2     = gsub('NEAR', 'W', MH),     check  = MH == mh2) %>%
  mutate(mh_not2 = gsub('NEAR', 'W', MH_NOT), check2 = mh_not2==MH_NOT) %>%
  mutate(gs2     = gsub('NEAR', 'W', GS),     check3 = gs2 == GS) %>%
  mutate(bs2     = gsub('NEAR', 'W', BS),     check4 = bs2 == BS) %>%
  mutate(ur2     = gsub('NEAR', 'W', Urban),  check5 = ur2 ==Urban)




Urban <- wos_scopus %>% 
  select(ur2) %>%
  filter(!is.na(ur2))

GS <- wos_scopus %>% 
  select(gs2) %>%
  filter(!is.na(gs2))

BS <- wos_scopus %>% 
  select(bs2) %>%
  filter(!is.na(bs2))


MH <- wos_scopus %>% 
  select(mh2) %>%
  filter(!is.na(mh2))


MH_NOT <- wos_scopus %>% 
  select(mh_not2) %>%
  filter(!is.na(mh_not2))



paste0('(', paste(Urban$ur2, collapse = ' OR '), ')')


paste0('(', paste(BS$bs2, collapse = ' OR '), ')')
paste0('(', paste(GS$gs2, collapse = ' OR '), ')')

paste0('(', paste(MH$mh2, collapse = ' OR '), ')')

paste0('(', paste(MH_NOT$mh_not2, collapse = ' OR '), ')')
```



## PubMed - done


## Embase 


## Google Scholar

# Test 