---
title: "mini-review"
author: "Yingjie"
date: "2023-03-05"
output:
  pdf_document: default
  html_document: default
---


# Setup
```{r, include=FALSE}
# To clear your environment
remove(list = ls())

Sys.setenv(LANG = "en")

## Load directories
# knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
# getwd()
# setwd(dirname(getwd()))

## Load common packages
getwd()
source("./code/_pkgs_dirs.R")
dir.raw   <- "./data/0005-covidence_export/data extraction/"
dir_share <- 'G:/Shared drives/Urban nature-health/projects/meta-analysis/figures/'


## Additional packages
library(rprojroot)
library(tidyverse)
library(splitstackshape) ## `cSplit()`
library(Hmisc)
library(rworldmap)
today <- format(Sys.time(), "%Y%m%d"); today ## "%Y%m%d%H%M"


save_plot <- F
save_plot <- T
```


```{r - helper data}
data(countryRegions,envir=environment(),package="rworldmap")
# str(countryRegions)

# ISO3:       ISO 3 letter country code
# ADMIN:      country name
# REGION:     7 region continent classification
# continent:  6 continents classification
```


```{r - functions}
source('./code/func_expand_col_to_long.R')
source('./code/func_clean_indicators.R')
source('./code/func_clean_indicatorsPro.R')
source('./code/func_clean_tools.R')
source('./code/func_plot_freq.R')
source('./code/func_alluvial.R')
source('./code/func_ggsave.R')

```



# Data import

## Data list
```{r include=FALSE}
fs <- list.files(path = dir.raw, full.names = T, pattern = '.csv$'); fs
# csv <- fs[1]
# names(df)
```


## Data for analysis 
```{r - data in Covidence, include=FALSE}
## Choose the most updated one for formal analysis ---------------------------------------
# csv <- "review_278532_20230305161741-test mini-review-analysis.csv"
# csv <- "review_278532_20230328115335.csv"   # 2023-03-28
csv <- "review_278532_20230427120514.csv"     # 2023-04-27 
csv <- "review_278532_20230616074045.csv"     # 2023-05-13, addressed 85 consensus 
csv <- "review_278532_20230703085230.csv"
csv <- "review_278532_20230920035224.csv"     # 2023-09-18, 30 consensus done for Extraction
csv <- "review_278532_20231208121506.csv"     # 2023-12-04, 38 consensus done

t <- basename(csv) %>% gsub('review_278532_', '', .) %>%
  str_sub(start = 1, end = 14)  %>%
  as.POSIXct(.,format="%Y%m%d%H%M%S") 
t

dd <- readr::read_csv(file = paste0(dir.raw, csv), show_col_types = F) %>%
  dplyr::mutate(date = t) %>%
  as.data.frame() %>%
  dplyr::rename(
    'id' = 'Covidence #',
    "Country" = "Country in which the study conducted",
    "Reviewer" = "Reviewer Name",
    'Indicator' = 'Mental health indicators',
    "Tools" = "Mental health measurement tools",
    "meet_criteria" = "Does this study meet the criteria for data extraction?"
  ) %>%
  dplyr::filter(!meet_criteria %in% c('No')) %>%
  dplyr::mutate(Tools   = gsub("Other\\: |Other\\:", "", Tools)) %>%
  dplyr::mutate(Country = gsub("Other\\: |Other\\:", "", Country)) %>%
  arrange(id, Reviewer) %>%
  as.data.frame()
```


```{r - data in gsheet}
library(googlesheets4)

### Use data from Google Doc
link <- 'https://docs.google.com/spreadsheets/d/1sVUU2FfSq3NChdM_Vhxc9sbm_eHAJtoKtEP_g3aIMn8/edit?usp=sharing'
dd.gsheet <- googlesheets4::read_sheet(link, sheet = 1) %>%
  dplyr::mutate(date = NA) %>%
  as.data.frame()

```


```{r - save as rds 📁,include=FALSE}
# names(dd)
unique(dd$Reviewer)


function_add_reviewer_id <- function(data) {
  d <- data %>%
    dplyr::mutate(Reviewer_id = case_when(
      Reviewer == 'Yingjie Li'    ~ 1, 
      Reviewer == 'Yuanyuan Mao'  ~ 2, 
      Reviewer == 'Zander Galli'  ~ 3, 
      Reviewer == 'Xin Lan'       ~ 4, 
      Reviewer == 'Emily Brieant' ~ 5, 
      Reviewer == 'Katherine Wu'  ~ 6,
      Reviewer == 'test person'   ~ 7,
      Reviewer == 'Mary Lee'      ~ 8,
      Reviewer == 'Consensus'     ~ 99
    )) %>%
    dplyr::select(id:Reviewer, Reviewer_id, everything()) %>%
    arrange(id, Reviewer_id, desc(date)) %>%
    dplyr::distinct(id, .keep_all = T) %>%
    as.data.frame()
}


df        <- function_add_reviewer_id(data = dd)
df.gsheet <- function_add_reviewer_id(data = dd.gsheet)

## save data for other analysis
f1 <- paste0('./data/0301-MA-input/df_covidenceFull_', today, '.rds'); f1
f2 <- paste0('./data/0301-MA-input/df_covidenceFull_', today, 'gsheet.rds'); f2
saveRDS(df,        file = f1)
saveRDS(df.gsheet, file = f2)
```


## Check consensus status
```{r}

df_check <- dd %>%
  arrange(id, Reviewer, desc(date)) %>%
  dplyr::distinct(id, Reviewer, .keep_all = T) %>%
  dplyr::select(1:5) %>%
  group_by(id) %>%
  add_count() %>%
  # dplyr::filter(n == 3) %>%  ## passed `consensus`
  dplyr::filter(n == 2) %>%    ## need `consensus`
  as.data.frame()

unique(df_check$id)


dd1 <- df_check %>%
  dplyr::distinct(id, Reviewer) %>%
  arrange(id, Reviewer) %>% 
  group_by(Reviewer) %>%
  summarise(id = str_c(id, collapse = ", ") )

##' a list of papers that have NOT been sent for concensus
dd2 <- aggregate(id ~ Reviewer, unique(df_check), paste, collapse = ", ")
```



# Data cleaning 


## Indicator

```{r - indicator, include=FALSE}

## load data
f <- paste0('./data/0301-MA-input/df_covidenceFull_', today, '.rds'); f
df <- readRDS(file = f)


## keep columns of interest, and clean data
dt <- df %>%
  dplyr::select(1:4, matches("Country|Mental health|Indicator|Tools")) %>%
  dplyr::select(!matches("duration", ignore.case = T)) %>%
  func_clean_indicators(data = .) %>%
  dplyr::arrange(!is.na(Indicator), Reviewer) %>%
  as.data.frame()




# names(dt)


## stat
## - by indicator
dt.ind <- dt %>%
  dplyr::filter(str_detect(string = Indicator, pattern = "exclude", negate = T)) %>%
  group_by(Indicator, Tools, Country) %>%
  dplyr::count() %>%
  ungroup() %>%
  as.data.frame()


## - clean and format
dt.ind.cl <- dt.ind %>% 
  expand_col_to_long(data = ., target_col = "Indicator") %>%
  dplyr::mutate(
    Indicator = gsub("emotions|Emotions", "Emotion", Indicator),
    Indicator = gsub(";", "", Indicator),
    ) %>%
  dplyr::filter(!Indicator %in% c('', NA)) %>%
  dplyr::filter(!Tools %in% c('', NA)) %>%
  as.data.frame()

dt.ind.clean <- dt.ind.cl %>% 
  group_by(Indicator) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  as.data.frame()
```


```{r - indicator bar}
dt.ind.clean %>%
  dplyr::slice_max(order_by = n, n = 20) %>%
  ggplot(aes(
    x = reorder(Indicator, n),
    y = n,
    # fill = n
  )) +
  geom_col() +
  coord_flip() +
  # scale_fill_distiller(name = '', palette = "Blues", guide = "colorbar", direction = 1) +
  xlab("") +
  ggtitle("Frequency of Mental health indicators") +
  theme_bw() +
  theme(
    # axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
    plot.title = element_text(size = 10, hjust = 1.2, face = 'bold')
    )

f <- paste0("mini-review_indicators_", today, ".png")
fname <- paste0(dir.fig, f)
w = 3
h = 5
func_ggsave(fname = fname, w = w, h = h)


## save to a shared Drive
fname <- paste0(dir_share, f); fname
func_ggsave(fname = fname, w = w, h = h)
```






## Tool

```{r - tool, include=FALSE}
## - by scale

dt.tool <- dt %>%
  ### -clean up the names of the tools
  dplyr::select(1:5, Tools, -Title) %>%
  dplyr::filter(str_detect(string = Tools, pattern = "exclude", negate = T)) %>%
  dplyr::mutate(Tool = gsub("Other: ", "", Tools)) %>%
  func_clean_tools(data = ., column_name = 'Tool') %>%
  as.data.frame()

dt.tool.expand <- dt.tool %>% 
  dplyr::filter(nchar(Tool) < 180) %>%
  expand_col_to_long(data = ., target_col = "Tool") %>%
  dplyr::mutate(
    Tool = gsub(".*Likert.*|.*likert.*", "Likert scale", Tool),
    # Tool = gsub(";", "", Tool),
    ) %>% 
  func_clean_tools(data = ., column_name = 'Tool') 

dt.tool.clean <- dt.tool.expand %>%
  group_by(Tool) %>%
  # dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  tally() %>%
  ungroup() %>%
  arrange(Tool) %>%
  as.data.frame()
```



```{r - tools selected for MA, include=FALSE}
## select the most used measures in literature for meta-analysis

### - 1. top 3
tools_selected <- c('POMS', 'GHQ-12', 'PANAS')

### - 2. adding more for data extraction 
tools_selected <- c('ROS',   # Restoration Outcome Scale
                    'PSS',   # Perceived Stress Scale
                    'PRS',   # Perceived Restorativeness Scale
                    'SF-12', # Short From Health Survey 36-item
                    'SF-36')

dt.tool.expand.selected <- dt.tool.expand %>% 
  dplyr::filter(Tool %in% tools_selected) %>%
  dplyr::select(-Tools) %>%
  arrange(Tool, id) %>%
  dplyr::mutate(id = paste0('#', id)) %>%
  as.data.frame()

f <- paste0('./data/0301-MA-input/', 'paperID_byTopTools2_', today, '.CSV'); f
readr::write_csv(x = dt.tool.expand.selected, file = f)
```



```{r - tool bar}

dt.tool.clean %>%
  dplyr::slice_max(order_by = n, n = 20) %>%
  plot_freq(data = ., var = 'Tool') +
  geom_text(
    aes(label = n), vjust = 0.5, hjust = 1.1, color = 'white', size = 3) +
  ggtitle("Frequency of Mental health\nmeasurement tools") +
  theme_bw() +
  theme(
    plot.title = element_text(size = 10, hjust = .5, face = 'bold'),
    plot.title.position = "plot", #NEW parameter. Apply for subtitle too.
    )

f <- paste0('mini-review_tools_bar_', today, '.png'); f
fname <- paste0(dir.fig, f)
func_ggsave(fname = fname, w = w, h = h)

###' save to a shared Drive
fname <- paste0(dir_share, f); fname
func_ggsave(fname = fname, w = w, h = h)
```


## Matching

```{r - indicator-tool matching}
set.seed(123)

## - need to better match indicator and scales for N vs N cases
dt.ind_match_scale <- dt %>%
  dplyr::select(-`Study ID`, -Title, -Country) %>%
  dplyr::mutate(
    n_ind  = 1+str_count(Indicator, ",|;"),
    n_tool = 1+str_count(Tools, ",|;")) %>%
  dplyr::filter(n_ind >1 & n_tool >1) %>%
  # dplyr::filter(Reviewer == 'Yingjie Li') %>%
  arrange(Indicator) %>%
  dplyr::slice(., sample(1:n()))
  


## YYM and YJL will each take a proportion, and manually fix the indicator-tool matching issue.  
dt.ind_match_scale1 <- dt.ind_match_scale %>%
  dplyr::slice_head(., prop = .51) %>%
  arrange(Indicator)


dt.ind_match_scale2 <- dt.ind_match_scale %>%
  dplyr::slice_tail(., prop = .51)%>%
  arrange(Indicator)


intersect(dt.ind_match_scale1$id, dt.ind_match_scale2$id)
intersect(dt.ind_match_scale2$id, dt.ind_match_scale1$id)

# readr::write_csv(x = dt.ind_match_scale1, file = paste0('./data/fix_indicator-tool_matching/', 'dt.ind_match_scale1.csv'))
# readr::write_csv(x = dt.ind_match_scale2, file = paste0('./data/fix_indicator-tool_matching/', 'dt.ind_match_scale2.csv'))

rm(dt.ind_match_scale1, dt.ind_match_scale2)

```


```{r - manual match, include=FALSE}
library(googlesheets4)
link <- 'https://docs.google.com/spreadsheets/d/1Tu7m6A7LOplbuXaLTYV0X3JUs0AhX90T0v-TcFTW3Yg/edit?usp=sharing'

### Footprint indicators
mat <- googlesheets4::read_sheet(link, sheet = 'MH_indicators_tools', skip = 1) 

matching <- mat %>%
  dplyr::select(MH_indicator, MH_tool_abbr) %>%
  # dplyr::distinct(ind, .keep_all = T) %>%
  dplyr::filter(
    !MH_indicator %in% c('x', '?', NA), 
    !MH_tool_abbr %in% c('x', '?', NA)
  ) %>%  
  dplyr::mutate(
    MH_indicator = gsub("\\s*\\([^\\)]+\\)", "", MH_indicator), # remove text within parenthesis 
    MH_tool_abbr = gsub("\\s*\\([^\\)]+\\)", "", MH_tool_abbr), # remove text within parenthesis 
    MH_indicator = Hmisc::capitalize(str_squish(trimws(MH_indicator))),
    MH_tool_abbr = Hmisc::capitalize(str_squish(trimws(MH_tool_abbr))),
  ) %>%  
  arrange(MH_indicator, MH_tool_abbr) %>%
  as.data.frame()
```




```{r - columns to be cleaned}
to.clean.ind <- dt.ind_match_scale %>% 
  expand_col_to_long(data = ., target_col = "Indicator") %>%
  dplyr::mutate(
    Indicator = gsub("emotions|Emotions", "Emotion", Indicator),
    Indicator = gsub(";", "", Indicator),
    ) %>% 
  group_by(Indicator) %>%
  tally() %>%
  dplyr::filter(!Indicator %in% c('', NA)) %>%
  as.data.frame()

to.clean.tool <- dt.ind_match_scale %>%
  dplyr::select(1:2, Tools) %>%
  dplyr::mutate(Tool = gsub("Other: ", "", Tools)) %>%
  func_clean_tools(data = ., column_name = 'Tool') %>%
  expand_col_to_long(data = ., target_col = "Tool") %>%
  dplyr::mutate(
    Tool = gsub(".*Likert.*|.*likert.*", "Likert scale", Tool),
    Tool = str_squish(trimws(Tool))
    ) %>% 
  dplyr::distinct(Tool, .keep_all = T) %>%
  dplyr::filter(str_starts(negate = T, pattern = "'|’", string = Tool)) %>%
  ungroup() %>%
  arrange(Tool) %>%
  as.data.frame()
```




```{r - varify matching, include=FALSE}
## make sure the indicator and tool names are cleaned and unified ------------------------
matching.1 <- matching %>%
  merge(x = ., y = to.clean.ind,  by.x = 'MH_indicator', by.y = 'Indicator', all = T) %>%
  arrange(!is.na(MH_tool_abbr)) %>%
  dplyr::select(-n) %>%
  merge(x = ., y = to.clean.tool, by.x = 'MH_tool_abbr', by.y = 'Tool', all = T) %>%
  arrange(!is.na(MH_indicator))
  


matching.final <- matching.1 %>%
  dplyr::filter(!is.na(MH_indicator) & !is.na(MH_tool_abbr)) %>%
  dplyr::select(1:2) %>%
  dplyr::mutate(pair = paste0(MH_indicator, '-', MH_tool_abbr))

f <- paste0('./data/MH_indicator_tool_matching_database.rds')
### Save a single object to a file
# saveRDS(object = matching, file = f)

### Restore it under a different name
# matching <- readRDS(file = f)
```



## Check data 

```{r - ❌ errors, include=FALSE}
dt_err <- dt %>%
  # dplyr::filter(str_detect(Indicator, fixed('Antidepressants', ignore_case = T))) %>% ##  
  # dplyr::filter(str_detect(Indicator, fixed('Hyperactivity', ignore_case = T))) %>% ##  
  # dplyr::filter(str_detect(Tools, fixed('4DSQ', ignore_case = T))) %>%
  # dplyr::filter(str_detect(Tools, fixed('PRS', ignore_case = T))) %>% # 
  # dplyr::filter(str_detect(Tools, fixed('Both SF', ignore_case = T))) %>% #
  dplyr::filter(str_detect(Tools, fixed('PNAS', ignore_case = T))) %>% # 
  # dplyr::filter(str_detect(Country, fixed('Virginia', ignore_case = T))) %>% # 
  as.data.frame()

# dt_err_ <- dt %>%
#   # dplyr::filter(id == '320') %>%
#   dplyr::filter(id == '134') %>%
#   dplyr::distinct(id, .keep_all = T) %>%
#   as.data.frame()
```



```{r - ✅ to-do list}
```
  [x] current indicator-scale matching approach needs to be improved, `dt.ind.tool`
  [] clean data in `matching.1`
  [] address consensus and keep unique paper id in the data `df`
  []
  []



## Region 

```{r - region - bar}

func_clean_country <- function(data) {
  d <- data %>%
    dplyr::mutate(
      ## clean and correct country names
      Country = case_when(
        str_detect(string = Country, pattern = 'Scotland|UK|England|United kingdom|The United Kingdom') ~ 'United Kingdom',
        str_detect(string = Country, pattern = 'Indonasia') ~ 'Indonesia',
        str_detect(string = Country, pattern = 'Malasia') ~ 'Malaysia',
        str_detect(string = Country, pattern = 'The Netherlands') ~ 'Netherlands',
        str_detect(string = Country, pattern = 'Danmark') ~ 'Denmark',
        str_detect(string = Country, pattern = 'Beigium') ~ 'Belgium',
        str_detect(string = Country, pattern = 'Brasil') ~ 'Brazil',
        str_detect(string = Country, pattern = 'Chili') ~ 'Chile',
        str_detect(string = Country, pattern = 'Czech') ~ 'Czechia',
        str_detect(string = Country, pattern = 'Virginia') ~ 'USA',
        # 
        T ~ Country)
      ) %>%
    dplyr::mutate(Country = trimws(Country)) %>%
    as.data.frame()
  return(d)
}

reg_ <- dt %>%
  dplyr::select(1, Country) %>%
  dplyr::filter(!is.na(Country)) %>%
  dplyr::filter(!Country %in% c('m', 'NA', 'Global', 'Europe', 'all over the world')) %>%
  group_by(Country) %>%
  tally() %>%
  as.data.frame()

region <- reg_ %>%
  expand_col_to_long(data = ., target_col = "Country") %>%
  dplyr::mutate(Country = ifelse(
      nchar(Country) > 3,
      str_to_title(Country),
      Country
    )) %>%
  func_clean_country(data = .) %>%
  group_by(Country) %>%
  dplyr::summarise_at('n', sum, na.rm = TRUE) %>%
  as.data.frame()


library(SDGdetector)
packageVersion('SDGdetector')

library(dplyr)
library(stringr)
library(ggplot2)
library(cowplot)


codelist.supp <- data.frame(
  country.name.en = c('USA'),
  iso3c = c('USA'),
  region = c('North America')
)
codelist <- SDGdetector::codelist_panel %>%
  dplyr::distinct(country.name.en, iso3c, region) %>%
  rbind(., codelist.supp) %>%
  dplyr::mutate(
    country.name.en = case_when(
      str_detect(string = iso3c, pattern = 'HKG') ~ 'Hong Kong',
      T ~ country.name.en)
  ) %>%
  dplyr::distinct(country.name.en, iso3c, region
)
  
shp <- SDGdetector::shp


func_add_region <- function(data) {
  d <- data %>%
    merge(x = ., 
          y = codelist, 
          by.x = 'Country', 
          by.y = 'country.name.en', all.x = T) %>%
    ## add more detailed region name info
    merge(x = ., 
          y = countryRegions %>%
            dplyr::select(ISO3, REGION, continent), 
          by.x = 'iso3c', 
          by.y = 'ISO3', all.x = T) %>%
    ## remove `region`, and rename `REGION` to `Region`
    dplyr::select(-region) %>%
    dplyr::rename('Region' = 'REGION') %>%
    arrange(!is.na(iso3c))
  
  return(d)
}

region_match <- region %>%
  func_add_region(.)
 

region_count <- region_match %>%
  group_by(
           # Country, 
           Region,
           iso3c
           ) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  arrange(n, Region, iso3c) %>%
  as.data.frame()


region_count %>% 
  dplyr::mutate(facet = ifelse(n>=5, 0, 1)) %>%
  # dplyr::slice_max(order_by = n, n = 20) %>%
  ggplot(aes(x = reorder(iso3c, n), 
             y = n,
             fill = Region
             )) +
  geom_col() +
  geom_text(aes(label = n), vjust = 0.5, hjust = 0, size = 3, color = 'gray20') +
  xlab('')+
  coord_flip() +
  facet_wrap(~facet, scales = 'free') +
  theme_bw() +
  theme(legend.position = c(.35, .27),
        strip.background = element_blank(), 
        strip.text = element_blank()
  )

f <- paste0('mini-review_paper_count_bar_', today, '.png'); f
fname <- paste0(dir.fig, f); fname
func_ggsave(fname = fname, w = 7, h = 4, save_png = T)
```


```{r - region - map}

region_count_sf <- region_count %>%
  merge(x= shp, y = ., by.x = 'iso_a3', by.y  = 'iso3c', all.x = T) 


region_count_sf %>%
  dplyr::filter(name != 'Antarctica') %>%
  ggplot(.) +
  geom_sf(aes(fill = n), size = 0.1, color = 'gray80') +
  # geom_sf_text(aes(label = iso_a3), colour = "gray", size =1) + 
  scale_fill_distiller(name= 'Count', palette = 'YlGnBu', direction = 1, na.value = "gray90") +
  # theme_bw() +
  theme_nothing() +
  theme(legend.position = c(0.06, 0.4))

f <- paste0('mini-review_paper_count_map_', today, '.png'); f
w_map = 6.4*2
h_map = 3.2*2

fname <- paste0(dir.fig, f); fname
func_ggsave(fname = fname, w = w_map, h = h_map)

fname <- paste0(dir_share, f); fname
func_ggsave(fname = fname, w = w_map, h = h_map)

```



```{r - ind + ctr}
dt.ind.cl_ctr  <- dt.ind.cl  %>%
  ## - clean `country` -------------------------------------------------------------------
  func_clean_country(.) %>%
  expand_col_to_long(data = ., target_col = "Country") %>%
  func_add_region(.) %>%
  group_by(Indicator, Region) %>%
  tally() %>%
  as.data.frame()


dt.ind.cl_ctr_flow  <- dt.ind.cl_ctr  %>%  
  tidyr::pivot_longer(names_to  = 'dimension', 
               values_to = 'layers', 
               cols = c('Indicator', 'Region')) %>%
  group_by(dimension) %>%
  dplyr::mutate(id_within_layers = row_number(dimension)) %>%
  arrange(dimension) %>%
  dplyr::rename(freq = n) %>%
  dplyr::mutate(
    dimension = factor(dimension, levels = c('Indicator', 'Region')),
    ) %>%
  group_by(layers) %>%
  dplyr::mutate(total = sum(freq, na.rm = T)) %>%
  as.data.frame()



library(ggalluvial)
width_my <- 1/2.5
sorted <- T  ## sorted by flow size
sorted <- NA ## default setting, sorted alphabetically 

indicator_n_min <- 5 ## only map indicators with more than 5 times
# Labeling small strata
labele_small <- 15


func_alluvial(data = dt.ind.cl_ctr_flow, indicator_n_min = 5, filename.postfix = 'indicator_region')
```



```{r - tool + ctr}
dt.tool_ctr  <- dt.ind  %>%
  dplyr::select(-Indicator) %>%
  ## - clean `tools` ---------------------------------------------------------------------
  dplyr::mutate(Tool = gsub("Other: ", "", Tools)) %>%
  func_clean_tools(data = ., column_name = 'Tool') %>%
  dplyr::filter(nchar(Tool) < 180) %>%
  dplyr::select(-Tools) %>%
  expand_col_to_long(data = ., target_col = "Tool") %>%
  dplyr::mutate(
    Tool = gsub(".*Likert.*|.*likert.*", "Likert scale", Tool),
    Tool = gsub("\\s*\\([^\\)]+\\)", "", Tool), # remove text within parenthesis 
    Tool = trimws(Tool)
    ) %>% 
  func_clean_tools(data = ., column_name = 'Tool') %>%
  # as.data.frame() 
  ## clean `country` ---------------------------------------------------------------------
  func_clean_country(.) %>%
  expand_col_to_long(data = ., target_col = "Country") %>%
  func_add_region(.) %>%
  group_by(Tool, Region) %>%
  tally() %>%
  as.data.frame()


dt.tool_ctr_flow  <- dt.tool_ctr  %>%  
  pivot_longer(names_to  = 'dimension', 
               values_to = 'layers', 
               cols = c('Tool', 'Region')) %>%
  group_by(dimension) %>%
  dplyr::mutate(id_within_layers = row_number(dimension)) %>%
  arrange(dimension) %>%
  dplyr::rename(freq = n) %>%
  dplyr::mutate(
    dimension = factor(dimension, levels = c('Tool', 'Region')),
    ) %>%
  group_by(layers) %>%
  dplyr::mutate(total = sum(freq, na.rm = T)) %>%
  as.data.frame()

func_alluvial(data = dt.tool_ctr_flow, indicator_n_min = 5, labele_small = 1, filename.postfix = 'tool_region')
```


```{r - ind + tool + region}
library(tidyverse)


## 1. selected countries for plot
country_selected <- region_count %>%
  slice_max(n = 3, order_by = n)
country_selected <- country_selected$iso3c
n_ctr <- length(country_selected)

## 2. all countries for plot
country_selected <- c()
n_ctr <- length(country_selected)


## - clean `tools` ---------------------------------------------------------------------
dt.ind.cl.1 <- dt.ind.cl %>%
  dplyr::mutate(
    n_tool = 1+str_count(Tools, ",|;")) %>%
  dplyr::filter(n_tool <= 1) %>%
  as.data.frame()

dt.ind.cl.2 <- dt.ind.cl %>%
  dplyr::mutate(
    n_tool = 1+str_count(Tools, ",|;")) %>%
  dplyr::filter(n_tool >1) %>%
  as.data.frame()


dt.ind.tool.1  <- dt.ind.cl.1  %>%
  dplyr::mutate(Tool = gsub("Other: ", "", Tools)) %>%
  func_clean_tools(data = ., column_name = 'Tool') %>%
  dplyr::filter(nchar(Tool) < 180) %>%
  dplyr::select(-Tools) %>%
  dplyr::mutate(
    Tool = gsub(".*Likert.*|.*likert.*", "Likert scale", Tool),
    Tool = gsub("\\s*\\([^\\)]+\\)", "", Tool), # remove text within parenthesis 
    Tool = trimws(Tool)
    ) %>% 
  group_by(Indicator, Tool, Country) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  as.data.frame()


dt.ind.tool.2  <- dt.ind.cl.2  %>%
  dplyr::mutate(Tool = gsub("Other: ", "", Tools)) %>%
  func_clean_tools(data = ., column_name = 'Tool') %>%
  dplyr::filter(nchar(Tool) < 180) %>%
  dplyr::select(-Tools) %>%
  expand_col_to_long(data = ., target_col = "Tool") %>%
  dplyr::mutate(
    Tool = gsub(".*Likert.*|.*likert.*", "Likert scale", Tool),
    Tool = gsub("\\s*\\([^\\)]+\\)", "", Tool), # remove text within parenthesis 
    Tool = trimws(Tool)
    ) %>% 
  group_by(Indicator, Tool, Country) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  ## matching 
  dplyr::mutate(matching = paste0(Indicator, '-', Tool)) %>%
  dplyr::filter(matching %in% unique(matching.final$pair)) %>%
  dplyr::select(-matching) %>%
  as.data.frame()
  
dt.ind.tool <- rbind(dt.ind.tool.1, dt.ind.tool.2)
  

## - clean `country` -------------------------------------------------------------------
dt.ind.tool.ctr  <- dt.ind.tool  %>%  
  func_clean_country(.) %>%
  expand_col_to_long(data = ., target_col = "Country") %>%
  func_add_region(.) %>%
  group_by(Indicator, Tool, Country, Region) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  as.data.frame()

if (n_ctr > 0) {
  dt.ind.tool.ctr2 <- dt.ind.tool.ctr %>%
    dplyr::filter(iso3c %in% country_selected)
} else {
  n_ctr <- ''
  dt.ind.tool.ctr2 <- dt.ind.tool.ctr
}
  

dt.ind.tool.region <- dt.ind.tool.ctr2 %>%
  group_by(Indicator, Tool, Region) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  # arrange(type_top) %>%
  dplyr::mutate(id = row_number()) %>%
  as.data.frame()


## - prep input for `ggalluvial` ---------------------------------------------------------
dtt  <- dt.ind.tool.region  %>%  
  pivot_longer(names_to = 'dimension', 
               values_to = 'layers', 
               cols = c('Indicator', 'Tool', 'Region')) %>%
  group_by(dimension) %>%
  dplyr::mutate(id_within_layers = row_number(dimension)) %>%
  arrange(dimension) %>%
  dplyr::rename(freq = n) %>%
  dplyr::mutate(
    dimension = factor(dimension, levels = c('Indicator', 'Tool', 'Region')),
    # layers = factor(layers, levels = org_levels)
    ) %>%
  group_by(layers) %>%
  dplyr::mutate(total = sum(freq, na.rm = T)) %>%
  as.data.frame()


func_alluvial(data = dtt, indicator_n_min = 3, labele_small = 20, w_p = 10, filename.postfix = 'indicator_tool_region2')

# f <- paste0('mini-review_mh_indicator_tool_pairs_min', indicator_n_min, '_ctr', n_ctr, '_', today, '.png')
# fname <- paste0(dir.fig, f); fname
# ggsave(filename = fname, plot = last_plot(), width = 10, height = 10, units = 'in', dpi = 300)
# 
# fname <- paste0(dir_share, f); fname
# ggsave(filename = fname, plot = last_plot(), width = 10, height = 10, units = 'in', dpi = 300)

```





