---
title: "mini-review"
author: "Yingjie"
date: "2023-03-05"
output:
  pdf_document: default
  html_document: default
---

# Load data

```{r}

## all data from Covidence
f <- paste0('./data/dt.rds')
dt <- readRDS(f)


## geocoded city data
f <- paste0('./data/dt_city_geocoded.rds')
dt_city <- readRDS(f) 

dt_city_count <- dt_city %>%
  dplyr::group_by(across(c(-id))) %>%
  dplyr::summarize(count = n())

hist(dt_city_count$count)
```




## Region 


```{r - region by year}
pub_byYear <- dt %>%
  dplyr::select(1:3, Country) %>%
  tidyr::separate(`Study ID`, into = c('Author', 'Year_pub'), sep = ' ', remove = F) %>%
  # group_by(Year_pub, Country) %>%
  dplyr::mutate(Year_pub = as.numeric(Year_pub)) %>%
  dplyr::filter(!is.na(Year_pub)) %>%
  group_by(Year_pub) %>%
  tally() %>%
  as.data.frame()

yr_min = min(pub_byYear$Year_pub, na.rm = T)
yr_max = max(pub_byYear$Year_pub, na.rm = T)


pub_byYear_p <- pub_byYear %>%
  ggplot(aes(x = Year_pub, 
             y = n,
             )) +
  geom_line(data = . %>% dplyr::filter(Year_pub < 2023), color = 'gray', linewidth =1
            )+
  geom_point() +
  geom_text(data = . %>% dplyr::filter(Year_pub < 2021), 
            aes(label = n), vjust = -0.5, hjust = 0.5, size = 3, color = 'gray20') +
  geom_text(data = . %>% dplyr::filter(Year_pub >= 2021), 
            aes(label = n), vjust = 0.5, hjust = -0.5, size = 3, color = 'gray20') +
  scale_x_continuous(breaks = c(seq(yr_min, yr_max, by=5), 2023)) +
  xlab('Year')+
  ylab('Number of publications')+
  theme_bw() +
  theme(panel.grid = element_blank()
    
  )
pub_byYear_p

f <- paste0(dir.fig, 'pub_byYear.png'); f
# func_ggsave(fname = f, w = 7, h = 4, save_png = T)
```

```{r - region - bar}

reg_ <- dt %>%
  dplyr::select(1, Country) %>%
  dplyr::filter(!is.na(Country)) %>%
  dplyr::filter(!Country %in% c('m', 'NA', 'Global', 'Europe', 'all over the world')) %>%
  group_by(Country) %>%
  tally() %>%
  as.data.frame()

region <- reg_ %>%
  expand_col_to_long(data = ., target_col = "Country") %>%
  dplyr::mutate(Country = ifelse(
      nchar(Country) > 3,
      str_to_title(Country),
      Country
    )) %>%
  func_clean_country(data = ., column_name = "Country") %>%
  group_by(Country) %>%
  dplyr::summarise_at('n', sum, na.rm = TRUE) %>%
  as.data.frame()


library(SDGdetector)
packageVersion('SDGdetector')

# library(countrycode)
# # names(codelist)
# nation.list <- codelist %>%
#   select(country.name.en, iso.name.en, un.name.en, cldr.name.en, iso2c, iso3c)

library(dplyr)
library(stringr)
library(ggplot2)
library(cowplot)

## World region data 1
codelist.supp <- data.frame(
  country.name.en = c('USA'),
  iso3c = c('USA'),
  region = c('North America')
)
codelist <- SDGdetector::codelist_panel %>%
  dplyr::distinct(country.name.en, iso3c, region) %>%
  rbind(., codelist.supp) %>%
  dplyr::mutate(
    country.name.en = case_when(
      str_detect(string = iso3c, pattern = 'HKG') ~ 'Hong Kong',
      T ~ country.name.en)
  ) %>%
  dplyr::distinct(country.name.en, iso3c, region)

## World region data 2
region_owid <- readr::read_csv('./data/continents-according-to-our-world-in-data.csv', show_col_types = FALSE) %>%
  dplyr::select(-Year) %>%
  dplyr::mutate(Code = gsub('OWID_', '', Code)) %>%
  dplyr::rename('name_owid' = 'Entity',
                'ISO3' = 'Code') %>%
  as.data.frame()

## World region data combined 
countryCode_region <- countryRegions %>%
  dplyr::mutate(REGION = ifelse(REGION=='Australia', 'Oceania', REGION)) %>%
  left_join(., region_owid, by = 'ISO3') %>%
  dplyr::select(1:REGION, Continent, continent, everything())
  
  
func_add_region <- function(data) {
  d <- data %>%
    merge(x = ., 
          y = codelist, 
          by.x = 'Country', 
          by.y = 'country.name.en', all.x = T) %>%
    ## add more detailed region name info
    merge(x = ., 
          y = countryCode_region %>%
            dplyr::select(ISO3, REGION, continent), 
          by.x = 'iso3c', 
          by.y = 'ISO3', all.x = T) %>%
    ## remove `region`, and rename `REGION` to `Region`
    dplyr::select(-region) %>%
    dplyr::rename('Region' = 'REGION') %>%
    arrange(!is.na(iso3c))
  
  return(d)
}

region_match <- region %>%
  func_add_region(.)
 

region_count <- region_match %>%
  group_by(
           # Country, 
           Region,
           iso3c
           ) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  arrange(n, Region, iso3c) %>%
  as.data.frame()


region_count %>% 
  dplyr::mutate(facet = ifelse(n>=5, 0, 1)) %>%
  # dplyr::slice_max(order_by = n, n = 20) %>%
  ggplot(aes(x = reorder(iso3c, n), 
             y = n,
             fill = Region
             )) +
  geom_col() +
  geom_text(aes(label = n), vjust = 0.5, hjust = 0, size = 3, color = 'gray20') +
  xlab('')+
  coord_flip() +
  facet_wrap(~facet, scales = 'free') +
  theme_bw() +
  theme(legend.position = c(.35, .27),
        strip.background = element_blank(), 
        strip.text = element_blank()
  )

f <- paste0('mini-review_paper_count_bar_', today, '.png'); f
fname <- paste0(dir.fig, f); fname
func_ggsave(fname = fname, w = 7, h = 4, save_png = T)
```


```{r - City - clean data}

# refer to `001a_city_geocoding_map.Rmd`
```


```{r - region - map}

shp <- SDGdetector::shp
# mollweide_crs <- "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
# robinson_crs  <- "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
##' Define the McBryde-Thomas Flat-Polar Quartic projection
##' https://map-projections.net/single-view/mcbryde-thomas-fp-quartic-interrupted
# mcbtfpq_proj4string <- "+proj=mbtfpq +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
# shp <- sf::st_transform(shp, mcbtfpq_proj4string)


region_count_sf <- region_count %>%
  merge(x= shp, y = ., by.x = 'iso_a3', by.y  = 'iso3c', all.x = T) 

pub_byregion_map <- region_count_sf %>%
  dplyr::filter(name != 'Antarctica') %>%
  ggplot(.) +
  geom_sf(aes(fill = n), size = 0.05, color = 'gray80') +
  # geom_sf_text(aes(label = iso_a3), colour = "gray", size =1) + 
  scale_fill_distiller(name= '', palette = 'YlGnBu', direction = 1, na.value = "gray90") +
  
  geom_point(data = dt_city_count, 
             aes(x = lon, y = lat, 
                 # color = count, 
                 size = count), color = 'red', shape = 16, alpha = 0.35) +
  scale_size_continuous(name = '', range = c(0.8, 3), breaks = c(1, 2, 4, 6, 8)) +
  # scale_color_gradient(low = "blue", high = "red") +

  # theme_bw() +
  theme_nothing() +
  theme(legend.position = c(0.1, 0.4), 
        legend.box = "horizontal") 

pub_byregion_map
# f <- paste0('mini-review_paper_count_map_', today, '.png'); f
# w_map = 6.4*2
# h_map = 3.2*2
# fname <- paste0(dir.fig, f); fname
# func_ggsave(fname = fname, w = w_map, h = h_map)
# 
# fname <- paste0(dir_share, f); fname
# func_ggsave(fname = fname, w = w_map, h = h_map)
```


```{r - by year by region map}
w_map <- 1.2
plot.with.inset <-
  ggdraw() +
  draw_plot(pub_byYear_p) +
  draw_plot(pub_byregion_map + theme(legend.text  = element_text(size = 8),
                                     legend.title = element_text(size = 9),
                                     legend.position = c(0.1, 0.3),
                                     legend.key.size = unit(0.8, "lines")), 
            x = -0.2, y = .35, width = w_map, height = w_map/2) +
  draw_label("", x = 0.02, y=0.95, fontface = 'bold')

plot.with.inset


fname <- paste0(dir.fig, 'pub_byYearRegion_map.png'); fname
func_ggsave(fname = fname, w = 6.5, h = 2.8, dpi = 600, save_png = T)
```



```{r - ind + ctr}
dt.ind.cl_ctr  <- dt.ind.cl  %>%
  ## - clean `country` -------------------------------------------------------------------
  func_clean_country(., column_name = "Country") %>%
  expand_col_to_long(data = ., target_col = "Country") %>%
  func_add_region(.) %>%
  group_by(Indicator, Region) %>%
  tally() %>%
  as.data.frame()


dt.ind.cl_ctr_flow  <- dt.ind.cl_ctr  %>%  
  tidyr::pivot_longer(names_to  = 'dimension', 
               values_to = 'layers', 
               cols = c('Indicator', 'Region')) %>%
  group_by(dimension) %>%
  dplyr::mutate(id_within_layers = row_number(dimension)) %>%
  arrange(dimension) %>%
  dplyr::rename(freq = n) %>%
  dplyr::mutate(
    dimension = factor(dimension, levels = c('Indicator', 'Region')),
    ) %>%
  group_by(layers) %>%
  dplyr::mutate(total = sum(freq, na.rm = T)) %>%
  as.data.frame()



library(ggalluvial)
width_my <- 1/2.5
sorted <- T  ## sorted by flow size
sorted <- NA ## default setting, sorted alphabetically 

indicator_n_min <- 5 ## only map indicators with more than 5 times
# Labeling small strata
labele_small <- 15


func_alluvial(data = dt.ind.cl_ctr_flow, indicator_n_min = 5, filename.postfix = '2d_indicator_region')
```



```{r - tool + ctr}
dt.tool_ctr  <- dt.ind  %>%
  dplyr::select(-Indicator) %>%
  ## - clean `tools` ---------------------------------------------------------------------
  dplyr::mutate(Tool = gsub("Other: ", "", Tools)) %>%
  func_clean_tools(data = ., column_name = 'Tool') %>%
  dplyr::filter(nchar(Tool) < 180) %>%
  dplyr::select(-Tools) %>%
  expand_col_to_long(data = ., target_col = "Tool") %>%
  dplyr::mutate(
    Tool = gsub(".*Likert.*|.*likert.*", "Likert scale", Tool),
    Tool = gsub("\\s*\\([^\\)]+\\)", "", Tool), # remove text within parenthesis 
    Tool = trimws(Tool)
    ) %>% 
  func_clean_tools(data = ., column_name = 'Tool') %>%
  # as.data.frame() 
  ## clean `country` ---------------------------------------------------------------------
  func_clean_country(., column_name = "Country") %>%
  expand_col_to_long(data = ., target_col = "Country") %>%
  func_add_region(.) %>%
  group_by(Tool, Region) %>%
  tally() %>%
  as.data.frame()


dt.tool_ctr_flow  <- dt.tool_ctr  %>%  
  pivot_longer(names_to  = 'dimension', 
               values_to = 'layers', 
               cols = c('Tool', 'Region')) %>%
  group_by(dimension) %>%
  dplyr::mutate(id_within_layers = row_number(dimension)) %>%
  arrange(dimension) %>%
  dplyr::rename(freq = n) %>%
  dplyr::mutate(
    dimension = factor(dimension, levels = c('Tool', 'Region')),
    ) %>%
  group_by(layers) %>%
  dplyr::mutate(total = sum(freq, na.rm = T)) %>%
  as.data.frame()

func_alluvial(data = dt.tool_ctr_flow, indicator_n_min = 5, labele_small = 1, filename.postfix = '2d_tool_region')
```


```{r - ind + tool + region}
library(tidyverse)


## 1. selected countries for plot
country_selected <- region_count %>%
  slice_max(n = 3, order_by = n)
country_selected <- country_selected$iso3c
n_ctr <- length(country_selected)

## 2. all countries for plot
country_selected <- c()
n_ctr <- length(country_selected)


## - clean `tools` ---------------------------------------------------------------------
dt.ind.cl.1 <- dt.ind.cl %>%
  dplyr::mutate(
    n_tool = 1+str_count(Tools, ",|;")) %>%
  dplyr::filter(n_tool <= 1) %>%
  as.data.frame()

dt.ind.cl.2 <- dt.ind.cl %>%
  dplyr::mutate(
    n_tool = 1+str_count(Tools, ",|;")) %>%
  dplyr::filter(n_tool >1) %>%
  as.data.frame()


dt.ind.tool.1  <- dt.ind.cl.1  %>%
  dplyr::mutate(Tool = gsub("Other: ", "", Tools)) %>%
  func_clean_tools(data = ., column_name = 'Tool') %>%
  dplyr::filter(nchar(Tool) < 180) %>%
  dplyr::select(-Tools) %>%
  dplyr::mutate(
    Tool = gsub(".*Likert.*|.*likert.*", "Likert scale", Tool),
    Tool = gsub("\\s*\\([^\\)]+\\)", "", Tool), # remove text within parenthesis 
    Tool = trimws(Tool)
    ) %>% 
  group_by(Indicator, Tool, Country) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  as.data.frame()


dt.ind.tool.2  <- dt.ind.cl.2  %>%
  dplyr::mutate(Tool = gsub("Other: ", "", Tools)) %>%
  func_clean_tools(data = ., column_name = 'Tool') %>%
  dplyr::filter(nchar(Tool) < 180) %>%
  dplyr::select(-Tools) %>%
  expand_col_to_long(data = ., target_col = "Tool") %>%
  dplyr::mutate(
    Tool = gsub(".*Likert.*|.*likert.*", "Likert scale", Tool),
    Tool = gsub("\\s*\\([^\\)]+\\)", "", Tool), # remove text within parenthesis 
    Tool = trimws(Tool)
    ) %>% 
  group_by(Indicator, Tool, Country) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  ## matching 
  dplyr::mutate(matching = paste0(Indicator, '-', Tool)) %>%
  dplyr::filter(matching %in% unique(matching.final$pair)) %>%
  dplyr::select(-matching) %>%
  as.data.frame()
  
dt.ind.tool <- rbind(dt.ind.tool.1, dt.ind.tool.2)
  

## - clean `country` -------------------------------------------------------------------
dt.ind.tool.ctr  <- dt.ind.tool  %>%  
  func_clean_country(., column_name = "Country") %>%
  expand_col_to_long(data = ., target_col = "Country") %>%
  func_add_region(.) %>%
  group_by(Indicator, Tool, Country, Region) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  as.data.frame()

if (n_ctr > 0) {
  dt.ind.tool.ctr2 <- dt.ind.tool.ctr %>%
    dplyr::filter(iso3c %in% country_selected)
} else {
  n_ctr <- ''
  dt.ind.tool.ctr2 <- dt.ind.tool.ctr
}
  

dt.ind.tool.region <- dt.ind.tool.ctr2 %>%
  group_by(Indicator, Tool, Region) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  # arrange(type_top) %>%
  dplyr::mutate(id = row_number()) %>%
  as.data.frame()


## - prep input for `ggalluvial` ---------------------------------------------------------
dimension_levels = c('Indicator', 'Tool', 'Region')
dimension_levels = c('Tool', 'Indicator', 'Region')
filename.postfix = paste(dimension_levels, collapse = "_") %>%
  paste0("3d_", .) %>%
  str_to_lower()

dtt  <- dt.ind.tool.region  %>%  
  pivot_longer(names_to = 'dimension', 
               values_to = 'layers', 
               cols = c('Indicator', 'Tool', 'Region')) %>%
  group_by(dimension) %>%
  dplyr::mutate(id_within_layers = row_number(dimension)) %>%
  arrange(dimension) %>%
  dplyr::rename(freq = n) %>%
  dplyr::mutate(
    dimension = factor(dimension, levels = dimension_levels),
    # layers = factor(layers, levels = org_levels)
    ) %>%
  group_by(layers) %>%
  dplyr::mutate(total = sum(freq, na.rm = T)) %>%
  as.data.frame()


func_alluvial(data = dtt, indicator_n_min = 3, labele_small = 20, w_p = 10, filename.postfix = filename.postfix)

# f <- paste0('mini-review_mh_indicator_tool_pairs_min', indicator_n_min, '_ctr', n_ctr, '_', today, '.png')
# fname <- paste0(dir.fig, f); fname
# ggsave(filename = fname, plot = last_plot(), width = 10, height = 10, units = 'in', dpi = 300)
# 
# fname <- paste0(dir_share, f); fname
# ggsave(filename = fname, plot = last_plot(), width = 10, height = 10, units = 'in', dpi = 300)

```





