---
title: "Untitled"
author: "Yingjie"
date: "`r Sys.Date()`"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


### To clear your environment
remove(list = ls())


source("./code/_pkgs_dirs.R")
library(tidyverse)

vv <- ''
```


## Data

```{r}
dir   <- "./data/0005-covidence_export/Quality assessment/"

csv <- "review_278532_20241012170155.csv"     


t <- basename(csv) %>% gsub('review_278532_', '', .) %>%
  str_sub(start = 1, end = 14)  %>%
  as.POSIXct(.,format="%Y%m%d%H%M%S") 
t

q <- readr::read_csv(file = paste0(dir, csv), show_col_types = F) %>%
  dplyr::mutate(date = t) %>%
  dplyr::rename(
    'id' = 'Covidence #',
    "Reviewer" = "Reviewer Name"
  ) %>%
  dplyr::select(!matches("supporting text|^---")) %>%
  arrange(id, Reviewer) %>%
  as.data.frame()
```




```{r - study design}
library(googlesheets4)
link <- 'https://docs.google.com/spreadsheets/d/1MZlUT5USAyydOE4CJQma3ZrmsYTwryUV3DbW5nZxL84/edit?usp=sharing'

### matching doc
gs <- googlesheets4::read_sheet(link, sheet = 'paperID_byTopTools', skip = 1) 

gs_all <- gs %>%
  dplyr::filter(!exclude %in% c('yes')) %>%
  dplyr::distinct(id, .keep_all = T) %>%
  dplyr::mutate(`study design` = gsub(' - crossover|-crossover', '', `study design`)) %>%
  as.data.frame()


gs_exp <- gs_all %>%
  dplyr::filter(!`study design` %in% c('Cross sectional study', 'Observational')) %>%
  dplyr::filter(str_detect(`study design`, 'Longitudinal', negate = T)) 


cat('\n\n There are \n\t', nrow(gs_all), 'included studies (obs + exp), and \n\t',
    nrow(gs_exp), 'exp studies')
```



```{r - study design - viz}

library(scales)
library(ggrepel)


# library(RColorBrewer)
# display.brewer.all(colorblindFriendly = TRUE)


## plot the stats of different study design
gs_all_stat <- gs_all %>%
  group_by(`study design`) %>%
  tally() %>%
  dplyr::mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  dplyr::mutate(labels = scales::percent(perc))


p1 <- gs_all_stat %>%
  ggplot(aes(x = reorder(`study design`, perc), y = n)) + 
  geom_col() +
  geom_text(aes(label = n), vjust = 0.5, hjust = -.3) +
  xlab('')+
  coord_flip()
# p1



p2 <- gs_all_stat %>%
  ggplot(data= ., aes(x="", y=n, fill=`study design`)) +
  geom_col() +
  
  geom_text(aes(label = labels), 
            position = position_stack(vjust = 0.5),
            size=3) +
  guides(fill = guide_legend(title = "Group")) +
  coord_polar("y") +
  scale_fill_brewer(palette = "Set2") +
  theme_void() 
# p2  


ggpubr::ggarrange(p1, p2, nrow = 2, labels = 'auto')

f <- paste0(dir.fig, 'qa_byDesign_both_', today, vv, '.png'); print(f)
ggsave(filename = f, width = 7, height = 4, units = 'in', dpi = 300)
```




```{r - study design - viz exp}
## plot the stats of different study design
gs_exp_stat <- gs_exp %>%
  group_by(`study design`) %>%
  tally() %>%
  dplyr::mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  dplyr::mutate(labels = scales::percent(perc))

# d2 <- gs_exp_stat %>%
#   dplyr::mutate(csum = rev(cumsum(rev(n))), 
#          pos = n/2 + lead(csum, 1),
#          pos = if_else(is.na(pos), n/2, pos)) %>%
#   as.data.frame()


p1 <- gs_exp_stat %>%
  ggplot(aes(x = reorder(`study design`, perc), y = n)) + 
  geom_col() +
  geom_text(aes(label = n), vjust = 0.5, hjust = -.3) +
  xlab('')+
  coord_flip()
# p1


p2 <- gs_exp_stat %>%
  ggplot(data= ., aes(x="", y=n, fill=`study design`)) +
  geom_col() +
  
  geom_text(aes(label = labels), 
            position = position_stack(vjust = 0.5),
            size=3) +
  # geom_label(aes(label = labels),
  #            # size = 3,
  #            position = position_stack(vjust = 0.5), 
  #            label.size = NA,  fill = alpha("white", 0.1),
  #            show.legend = FALSE) +
  
  # geom_label_repel(data = d2,
  #                  aes(y = pos, label = labels),
  #                  label.size = NA,  fill = alpha("white", 0.1),
  #                  size = 4.5, nudge_x = 1, show.legend = FALSE) +
  guides(fill = guide_legend(title = "Group")) +
  coord_polar("y") +
  scale_fill_brewer(palette = "Set2") +
  theme_void() 
# p2  


ggpubr::ggarrange(p1, p2, nrow = 2, labels = 'auto')

f <- paste0(dir.fig, 'qa_byDesign_exp_', today, vv, '.png'); print(f)
ggsave(filename = f, width = 7, height = 4, units = 'in', dpi = 300)
```




```{r - clean qa data}
source('./code/func_add_reviewer_id.R')
qa <- func_add_reviewer_id_qa(data = q) %>%
  ## keep one reviewer's data based on priority setting
  arrange(id, Reviewer_id, desc(date)) %>%
  dplyr::distinct(id, .keep_all = T) %>%
  dplyr::select(-Reviewer_id) %>% 
  as.data.frame()

## remove strings after ":" in the column names
names(qa) <- sub(":.*", "", names(qa))

qa_obs_data <- qa %>%
  dplyr::filter(!is.na(OBS1)) %>%
  dplyr::select(1:OBS8) 
  
  
qa_obs <- qa_obs_data %>%
  pivot_longer(cols = 5:ncol(.), names_to = 'Item') %>%
  dplyr::mutate(rate = case_when(
    value == 'Yes' ~ 'Low risk',
    value == 'No'  ~ 'High risk',
    value == 'Not applicable' ~ 'Unclear',
    TRUE ~ value
  )) %>%
  dplyr::mutate(Items = case_when(
    Item == 'OBS1' ~ 'criteria for inclusion of samples',
    Item == 'OBS2' ~ 'description of the study participants',
    Item == 'OBS3' ~ 'measurement of exposure',
    Item == 'OBS4' ~ 'measurement of the condition',
    Item == 'OBS5' ~ 'confounding factors identified',
    Item == 'OBS6' ~ 'strategies to confounding factors',
    Item == 'OBS7' ~ 'measurement of outcomes',
    Item == 'OBS8' ~ 'appropriate statistical analysis',
    TRUE ~ Item
  )) %>%
  dplyr::mutate(Items = str_to_sentence(Items)) %>%
  group_by(Items, rate) %>%
  tally()


qa_exp_data <- qa %>%
  ## filter exp studies
  dplyr::mutate(id = paste0('#', id)) %>%
  dplyr::filter(id %in% unique(gs_exp$id)) %>%
  dplyr::select(-c(OBS1:OBS8), -date) %>%
  dplyr::filter(!id %in% c('852', '2222'))

## to check if some studies have not been assessed
ls_gs <- unique(gs_exp$id)
ls_qa <- unique(qa_exp_data$id)
setdiff(x = ls_qa, y = ls_gs)
setdiff(y = ls_qa, x = ls_gs)


## plot 
qa_exp <- qa_exp_data %>%
  pivot_longer(cols = 5:ncol(.), names_to = 'Items') %>%
  dplyr::mutate(rate = gsub(' of bias', '', value),
                rate = stringr::str_squish(rate)) %>%
  group_by(Items, rate) %>%
  tally()

cat(nrow(qa_obs_data), 'unique observational papers were included in quality assessment.\n') # 50
cat(nrow(qa_exp_data), 'unique experimental  papers were included in quality assessment.\n') # 84


## save data
f <- paste0(dir.output, 'qa_exp_data.csv')
readr::write_csv(x = qa_exp_data, file = f)
  
f <- paste0(dir.output, 'qa_obs_data.csv')
readr::write_csv(x = qa_obs_data, file = f)
```


```{r  - viz}
# library
library(ggplot2)

# # Stacked
# qa_obs %>%
#   ggplot(., aes(fill=value, y=n, x=items)) + 
#   geom_bar(position="stack", stat="identity") +
#   coord_flip() +
#   theme_minimal()

func_plot_qa <- function(data) {
  p <- data %>%
    group_by(Items) %>%
    dplyr::mutate(Percent = n / sum(n, na.rm = T),
                  Label = scales::percent(Percent)) %>%
    ungroup() %>%
    ggplot(., aes(fill=rate, y=Percent, x=Items)) + 
    # Stacked + percent
    geom_bar(position="fill", stat="identity") +
    geom_text(aes(label = Label), position = position_stack(vjust = 0.5), size =2) +
    scale_y_continuous(labels = scales::percent_format()) +
    labs(fill='Risk of Bias') +
    coord_flip() +
    theme_minimal() +
    theme(axis.title = element_blank())  # Remove the x-axis title
  return(p)
}

p1 <- func_plot_qa(data = qa_obs)
p2 <- func_plot_qa(data = qa_exp)


## save figure for experimental studies
f <- paste0(dir.fig, 'qa_exp_', today, vv, '.png'); print(f)
ggsave(plot = p2, filename = f, width = 7, height = 2, units = 'in', dpi = 300)


## save combined data for both observational and experimental studies
ggpubr::ggarrange(p1, p2, labels = 'auto', ncol = 1, align = 'v')

f <- paste0(dir.fig, 'qa_', today, vv, '.png'); print(f)
ggsave(filename = f, width = 7, height = 4, units = 'in', dpi = 300)


```




```{r - data - RCT, fig.height=2, fig.width=7}
gs_rct <- gs_exp %>%
  dplyr::filter(`study design` == 'RCT')

qa_rct_data <- qa_exp_data %>%
  dplyr::filter(id %in% unique(gs_rct$id))

## save data 
f <- paste0(dir.output, 'qa_rct_data_', today, '.xlsx'); f
writexl::write_xlsx(x = qa_rct_data, path = f)

## to check if some studies have not been assessed
ls_gs <- unique(gs_rct$id)
ls_qa <- unique(qa_rct_data$id)
setdiff(x = ls_qa, y = ls_gs)
setdiff(y = ls_qa, x = ls_gs)


## plot
qa_rct <- qa_rct_data %>%
  pivot_longer(cols = 5:ncol(.), names_to = 'Items') %>%
  dplyr::mutate(rate = gsub(' of bias', '', value),
                rate = stringr::str_squish(rate)) %>%
  group_by(Items, rate) %>%
  tally()

func_plot_qa(data = qa_rct)
f <- paste0(dir.fig, 'qa_rct_', today, vv, '.png'); print(f)
ggsave(filename = f, width = 7, height = 4/2, units = 'in', dpi = 300)
```

