---
title: "MA_exposure"
author: "Yingjie"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: inline
---


# Setup 
```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


### To clear your environment
# remove(list = ls())


## Load common packages
source("./code/_pkgs_dirs.R")

## Additional packages
library(googlesheets4)
library(rprojroot)
library(tidyverse)
library(stringr)
library(splitstackshape) ## `cSplit()`
library(Hmisc)
library(rworldmap)
library(ggpubr)

library(meta)
library(metafor)

```


```{r - functions}
source('./code/func_expand_col_to_long.R')
source('./code/func_clean_indicators.R')
source('./code/func_clean_indicatorsPro.R')
source('./code/func_clean_tools.R')
source('./code/func_clean_exposure.R')
source('./code/func_clean_effectsize.R')
source('./code/func_clean_nature.R')
source('./code/func_to_sd.R')
source('./code/func_fill_c2_from_c1.R')
source('./code/func_cell_mean.R')

source('./code/func_plot_freq.R')
source('./code/func_alluvial.R')
source('./code/func_ggsave.R')
```


# Data

  Load data
```{r}

## Pre-cleaned data (Covidence data only)
f <- paste0(dir.output, "df_cleaned.RDS")


df <- readRDS(f)
```



## Prepare data for MA

### * Coefficient-based outcomes ---

```{r - function}

###' subset papers that examined `exposure_type_i`
###' 

func_exp_subset <- function(df, exposure_type_i, mh_tool) {
  
  ## get paper id
  exp_sub <- df_exp_l %>%
    dplyr::filter(exposure_type %in% exposure_type_i)
  exp_sub_id <- unique(exp_sub$id) %>% sort()

  ## subset based paper id
  exp_sub_df <- df %>%
    dplyr::filter(id %in% exp_sub_id) %>%
    dplyr::filter(stringr::str_detect(Tools, paste(mh_tool, collapse = "|"))) %>%
    
    ## subset cols -----------------------------------------------------------------------
    dplyr::select(id:`Effect size indices`, effect_size_indices, 
                  everything()) %>%
    dplyr::select(id:Country, 
                  all_of(cols_keep), 
                  n_participants, buffers, buffers_unit,
                  effect_size_indices:ncol(.)) %>%
    dplyr::select(-c('Title', 'Reviewer_id', 'meet_criteria')) %>% ## keep "Reviewer" to match data from gsheet
    dplyr::select(-contains(c('Please specify the tables', 'Additional comments'))) %>%
    as.data.frame()
  
  return(exp_sub_df)
  
}


# df_exp_tool_flow3 <- df_exp_l_toolL %>%
#   dplyr::filter(Tool %in% tool_selected) %>% 
```


#### - GHQ-12
```{r}
mh_tool           <- "GHQ-12"

##' filter exposure types based on this broader category
##' It is likely this does not cover all the list in papers
unique(df_exp_l$exposure_type)
# unique(df_exp_l$exposure_type_t1)
# exposure_type_i   <- 'L1 - neighborhood/residential exposure'
exposure_type_i   <- c('Residential')

effect_size_ind_i <- c('coef')
  

## test 
# df_test <- df %>%
#   dplyr::mutate(effect_size_indices = `Effect size indices`) %>%
#   func_clean_effectsize(data = .) %>%
#   dplyr::select(effect_size_indices, `Effect size indices`) %>%
#   dplyr::mutate(len = str_length(effect_size_indices)) %>%
#   arrange(desc(len)) %>%
#   as.data.frame()

exp_sub_df <- func_exp_subset(df = df, exposure_type_i = exposure_type_i, mh_tool = mh_tool)
sub_ghq <- exp_sub_df

## save for later use
f <- paste0('./data/0301-MA-input/', 'sub_', paste(mh_tool, sep = '', collapse = '_'), '.RData'); f
save(mh_tool, exposure_type_i, effect_size_ind_i, exp_sub_df, file = f)

f <- gsub('RData', 'rds', f); f
saveRDS(exp_sub_df, file = f)


## for RA/Carl
f <- gsub('rds', 'csv', f); f
readr::write_csv(x = exp_sub_df, file = f)
```



#### - SF-12, SF-36
```{r}
mh_tool <- c("SF-12", "SF-36")


## test 
df_test <- df %>%
  # dplyr::filter(id %in% exp_sub_id) %>%
  dplyr::filter(stringr::str_detect(Tools, paste(mh_tool, collapse = "|"))) %>%
  as.data.frame()

exp_sub_df <- func_exp_subset(df = df, exposure_type_i = exposure_type_i, mh_tool = mh_tool)
sub_sf <- exp_sub_df



## save for later use
## save for later use
f <- paste0('./data/0301-MA-input/', 'sub_', paste(mh_tool, sep = '', collapse = '_'), '.RData'); f
save(mh_tool, exposure_type_i, effect_size_ind_i, exp_sub_df, file = f)

f <- gsub('RData', 'rds', f); f
saveRDS(exp_sub_df, file = f)
```


#### - WEMWBS
```{r}
mh_tool <- c('WEMWBS')


## test 
df_test <- df %>%
  # dplyr::filter(id %in% exp_sub_id) %>%
  dplyr::filter(stringr::str_detect(Tools, paste(mh_tool, collapse = "|"))) %>%
  as.data.frame()

exp_sub_df <- func_exp_subset(df = df, exposure_type_i = exposure_type_i, mh_tool = mh_tool)
sub_WEMWBS <- exp_sub_df

## save for later use
f <- paste0('./data/0301-MA-input/', 'sub_', paste(mh_tool, sep = '', collapse = '_'), '.RData'); f
save(mh_tool, exposure_type_i, effect_size_ind_i, exp_sub_df, file = f)

f <- gsub('RData', 'rds', f); f
saveRDS(exp_sub_df, file = f)
```

#### - WHO-5
```{r}
mh_tool <- c('WHO-5')


## test 
df_test <- df %>%
  # dplyr::filter(id %in% exp_sub_id) %>%
  dplyr::filter(stringr::str_detect(Tools, paste(mh_tool, collapse = "|"))) %>%
  as.data.frame()

exp_sub_df <- func_exp_subset(df = df, exposure_type_i = exposure_type_i, mh_tool = mh_tool)
sub_who5 <- exp_sub_df

## save for later use
f <- paste0('./data/0301-MA-input/', 'sub_', paste(mh_tool, sep = '', collapse = '_'), '.RData'); f
save(mh_tool, exposure_type_i, effect_size_ind_i, exp_sub_df, file = f)

f <- gsub('RData', 'rds', f); f
saveRDS(exp_sub_df, file = f)
```



#### - PSS - obs
```{r}
mh_tool <- c('PSS')


## test 
df_test <- df %>%
  # dplyr::filter(id %in% exp_sub_id) %>%
  dplyr::filter(stringr::str_detect(Tools, paste(mh_tool, collapse = "|"))) %>%
  as.data.frame()

exp_sub_df %>%
  group_by(effect_size_indices) %>% count(effect_size_indices)

exp_sub_df <- func_exp_subset(df = df, exposure_type_i = exposure_type_i, mh_tool = mh_tool)
sub_pss <- exp_sub_df

## save for later use
f <- paste0('./data/0301-MA-input/', 'sub_', paste(mh_tool, sep = '', collapse = '_'), '_obs.RData'); f
save(mh_tool, exposure_type_i, effect_size_ind_i, exp_sub_df, file = f)

f <- gsub('RData', 'rds', f); f
saveRDS(exp_sub_df, file = f)
```



#### - PHQ
```{r}
mh_tool <- c('PHQ')


## test 
df_test <- df %>%
  # dplyr::filter(id %in% exp_sub_id) %>%
  dplyr::filter(stringr::str_detect(Tools, paste(mh_tool, collapse = "|"))) %>%
  as.data.frame()



exp_sub_df <- func_exp_subset(df = df, exposure_type_i = exposure_type_i, mh_tool = mh_tool)
exp_sub_df %>%
  group_by(effect_size_indices) %>% count(effect_size_indices)


sub_phq <- exp_sub_df

## save for later use
f <- paste0('./data/0301-MA-input/', 'sub_', paste(mh_tool, sep = '', collapse = '_'), '_obs.RData'); f
# save(mh_tool, exposure_type_i, effect_size_ind_i, exp_sub_df, file = f)
# 
# f <- gsub('RData', 'rds', f); f
# saveRDS(exp_sub_df, file = f)
```



#### - GAD
```{r}

```




## Format data

### Load input data

  Now, each paper can include data from multiple models, and they are presented in columns. 
We need to put all data on models in rows. 

```{r}

# source('./code/010s1_loop_format_data.R')


##' 1. when 'PSS' is mainly used in `obs` studies
mh_tool_obs <- c('GHQ-12', 'SF-12', 'SF-36', 'WEMWBS', 'WHO-5', 'PSS'); design <- 'obs'
mh_tool_exp <- c('PANAS', 'POMS', 'ROS', 'STAI', 'SVS');                design <- 'exp'


##' 2. when 'PSS' is mainly used in `exp` studies
mh_tool_obs <- c('GHQ-12', 'SF-12', 'SF-36', 'WEMWBS', 'WHO-5'); design <- 'obs'
mh_tool_exp <- c('PANAS', 'POMS', 'ROS', 'STAI', 'SVS', 'PSS', 'DASS-21');  design <- 'exp'
```



### Batch

  Run this chunk only if you have already executed one of the selected MH tool chunks above.
  
```{r - 1. batch one}
##' 1. Choose one as input --------------------------------
##'   `mh_tool`, `exposure_type_i`, `effect_size_ind_i`, `exp_sub_df`
fi <- paste0('./data/0301-MA-input/', 'sub_', paste(mh_tool, collapse = '_'), '.RData'); fi

load(fi)
source('./code/010s1_loop_format_data.R')
fi.c <- gsub('.rds|.RData', '_cleaned.csv', fi); fi.c
readr::write_csv(x = exp_sub_mods_print, file = fi.c)
```


```{r - 2. loop all, eval=FALSE, include=FALSE}
##' 1. loop all -----------------------------------
##' 
fs <- list.files(path = './data/0301-MA-input/', pattern = '^sub_.*.RData', full.names = T) %>% sort()
fs
for (fi in fs) {
  print(basename(f))
  # exp_sub_df <- readRDS(f)
  load(fi)
  ##
  source('./code/010s1_loop_format_data.R')
  fi.c <- gsub('.rds|.RData', '_cleaned.csv', fi); fi.c
  readr::write_csv(x = exp_sub_mods_print, file = fi.c)
}

```

