---
title: "MA_exposure"
author: "Yingjie"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### To clear your environment
remove(list = ls())

## Load directories
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
getwd()
setwd(dirname(getwd()))

getwd()
## Load common packages
source("./code/_pkgs_dirs.R")
## Additional packages
library(rprojroot)
library(tidyverse)
library(stringr)
library(splitstackshape) ## `cSplit()`
library(Hmisc)
library(rworldmap)
today <- format(Sys.time(), "%Y%m%d"); today ## "%Y%m%d%H%M"


source('./code/func_expand_col_to_long.R')
source('./code/func_plot_freq.R')
```



## load data
```{r}

df <- readRDS(file = "./data/0301-MA-input/df_covidenceFull.rds")
# names(df)
```


## clean data
```{r}

df_exp <- df %>%
  dplyr::rename('exposure_type' = 'Nature exposure type') %>%
  dplyr::select(1:6, exposure_type) %>%
  dplyr::filter(!is.na(exposure_type)) %>%
  dplyr::mutate(exposure_type = gsub("Other: |Other:", "", exposure_type)) %>%
  dplyr::mutate(exposure_type = gsub("\\s*\\([^\\)]+\\)", "", exposure_type)) %>% # remove text within parenthesis
  as.data.frame()

df_exp_l <- df_exp %>% 
  expand_col_to_long(data = ., target_col = 'exposure_type') %>%
  
  as.data.frame()


df_exp_l_stat <- df_exp_l %>% 
  ## clean the text data
  dplyr::mutate(
    exposure_type = gsub("L4 physical activity", "L4 - physical activity in nature", exposure_type),
    exposure_type = gsub("L1 surrounding greenness", "L1 - neighborhood/residential exposure", exposure_type),
    exposure_type = gsub("L2 objective accessibility", "L2 - objective accessibility", exposure_type),
    ) %>%
  group_by(exposure_type) %>%
  dplyr::count() %>%
  ungroup() %>%
  as.data.frame()
  
```


## plot
```{r}
plot_freq(data = df_exp_l_stat, var = 'exposure_type') +
   geom_text(aes(label = n), vjust = .5, hjust = 0)
```

## analysis
```{r}
exp_sub <- df_exp_l %>%
  dplyr::filter(exposure_type == 'L1 - neighborhood/residential exposure')

exp_sub_id <- unique(exp_sub$id)

exp_sub_df <- df %>%
  dplyr::filter(id %in% exp_sub_id) %>%
  dplyr::filter(str_detect(Tools, "GHQ-12")) %>%
  dplyr::mutate(Effect_size_indices = gsub("Other: |Other:", "", `Effect size indices`),
                Effect_size_indices = gsub("=.*", "", Effect_size_indices),
                Effect_size_indices = gsub("corr_linear|corr_logi|regression coefficient", "coefficients", Effect_size_indices),
                Effect_size_indices = trimws(Effect_size_indices)
                ) %>%
  dplyr::select(id:`Effect size indices`, Effect_size_indices, everything()) %>%
  dplyr::select(id, Effect_size_indices:ncol(.)) %>%
  as.data.frame()


## for model 1
# exp_sub_mod1 <- exp_sub_df %>%
#   dplyr::select(id, starts_with("Model 1 ") & !contains("measurement", ignore.case = TRUE))
# 
# exp_sub_mod11 <- exp_sub_df %>%
#   dplyr::select(id, starts_with("Model 11 "))


exp_sub_mod_l <- data.frame()
for (i in 1:20) {
  # print(i)
  mod_id <- paste0("Model ", i, " ")
  exp_sub_mod <- exp_sub_df %>%
    dplyr::select(id, Effect_size_indices, `Health outcome direction`, 
                  starts_with(mod_id) & !contains("measurement", ignore.case = TRUE)) %>%
    dplyr::mutate(model_id = i) %>%
    dplyr::select(id, Effect_size_indices, model_id, `Health outcome direction`, everything())
  
  colnames(exp_sub_mod) <- sub(mod_id, "", colnames(exp_sub_mod))
  
  exp_sub_mod_l <- rbind(exp_sub_mod_l, exp_sub_mod)
}

rm(exp_sub_mod)
```



```{r}
### clean up the negative sign "-" in data
test <- exp_sub_mod_l %>%
  dplyr::filter(id == 504)
m <- gsub(' ', '', test$Mean)
sign <- m[1] %>% substr(., 1, 1)
# mm <- gsub(sign, '-', m)
# mm
# as.numeric(mm)



exp_sub_mods <- exp_sub_mod_l %>%
  dplyr::filter(!is.na(Mean)) %>%
  dplyr::rename(Mean_raw = Mean) %>%
  dplyr::rename(CI_95_lower_raw = CI_95_lower) %>%
  dplyr::mutate(
    Mean = as.character(Mean_raw),
    Mean = gsub(sign, "-", Mean_raw),
    Mean = gsub(" ", "", Mean), 
    Mean = str_squish(Mean),
    Mean = trimws(Mean),
    Mean = as.numeric(Mean),
    Mean = case_when(
      Effect_size_indices == 'coefficients' & `Health outcome direction` == "Higher is better" ~ -Mean,
      Effect_size_indices == 'or' & `Health outcome direction` == "Higher is better" ~ 1-(Mean-1),
      TRUE ~ Mean
      ),
    
    CI_95_lower = as.character(CI_95_lower_raw),
    CI_95_lower = gsub(sign, "-", CI_95_lower),
    CI_95_lower = gsub(" ", "", CI_95_lower), 
    CI_95_lower = trimws(CI_95_lower),
    CI_95_lower = as.numeric(CI_95_lower),
    CI_95_lower = ifelse(`Health outcome direction` == "Higher is better", -CI_95_lower, CI_95_lower),
    
    N = gsub(" ", "", N), 
    N = as.numeric(N),
    
    
    ) %>%
  dplyr::select(id:Mean_raw, Mean, CI_95_lower_raw, CI_95_lower, everything()) %>%
  arrange(Effect_size_indices, id, model_id) %>%
  as.data.frame()
```


### Coefficients
```{r}
unique(exp_sub_mods$Effect_size_indices)


exp_sub_mods_coef <- exp_sub_mods %>%
  dplyr::filter(Effect_size_indices == 'coefficients') %>%
  as.data.frame()
```


#### psychmeta
```{r}
# devtools::install_github("psychmeta/psychmeta")
library(psychmeta)

ma_res <- ma_r(
  data = exp_sub_mods_coef,
  rxyi = Mean, 
  n = N, 
  # ma_method = "ic", #individual corrections
  # construct_x = NULL,
  # construct_y = NULL,
  sample_id = id, 
  ### What are your moderators and which ones are categorical?
  # moderators = NULL, cat_moderators = TRUE,
  # wt_type = "sample_size",
  ### What are your reliability coefficients?
  # rxx = NULL, ryy = NULL,
  )

summary(ma_res)

ma_res <- plot_funnel(ma_res)
#> Funnel plots have been added to 'ma_obj' - use get_plots() to retrieve them.
ma_res <- plot_forest(ma_res)
#> Forest plots have been added to 'ma_obj' - use get_plots() to retrieve them.
#> 

# get_plots(ma_res)[["forest"]][[2]]

# get_plots(ma_res)[["funnel"]][[2]]

get_plots(ma_res)[["forest"]][[1]][["moderated"]][["barebones"]]
get_plots(ma_res)[["forest"]][[1]][["unmoderated"]][["barebones"]]
```


```{r}
meta.object <- ma_res

heterogeneity(meta.object)-> meta.object
plot_forest(meta.object)-> meta.object
plot_funnel(meta.object)-> meta.object
meta.object$heterogeneity$`analysis id: 1`$individual_correction$true_score
meta.object$forest$`analysis id: 1`$unmoderated$individual_correction$ts
meta.object$funnel$`analysis id: 1`$individual_correction$true_score

```




```{r}
### - sensitivity analyses
# ma_obj <- sensitivity(ma_res,
#                       leave1out = TRUE,
#                       bootstrap = TRUE,
#                       cumulative = TRUE,
# 
#                       sort_method = "weight",
# 
#                       boot_iter = 100,
#                       boot_conf_level = 0.95,
#                       boot_ci_type = "norm")
```

#### metafor
```{r}
# load the metafor package
library(metafor)

## meta-analysis on the correlation between employment interview assessments
##     and job performance (using r-to-z transformed correlation for the analysis)
#' example data -- `dat.mcdaniel1994`
#' 
dat <- escalc(measure="ZCOR", ri=Mean, ni=N, data=exp_sub_mods_coef)
res <- rma(yi, vi, data=dat)
res
predict(res, transf=transf.ztor)

# outlier/influence diagnostics
par(mar=c(5,6,4,2))
plot(influence(res), cex=0.8, las=1)
```


```{r - forest & funnel}
### forest plot --------------------------------------------------------------------------
# forest(res)
# forest(res, addpred=TRUE, header=TRUE)
# print(forest(res, addpred=TRUE, header=TRUE))
xlim_custmize = c(-1,1)
# forest(res, addpred=TRUE, header=TRUE, xlim=xlim_custmize)
# forest(res, addpred=TRUE, header=TRUE, xlim=xlim_custmize, atransf=exp)
forest(res, addpred=TRUE, header=TRUE, xlim=xlim_custmize, atransf=exp, at=log(c(.6, .8, 1, 1.2, 1.5)))



### funnel plot --------------------------------------------------------------------------
# funnel(res)
# funnel(res, ylim=c(0,.08), las=1)
funnel(res, ylim=c(0,.08), las=1, digits=list(2L,2))


# contour-enhanced funnel plot
funnel(dat$yi, dat$vi, yaxis="seinv",
       # xlim=c(-.5, .5),
       ylim=c(10, 200), 
       xaxs="i", yaxs="i", las=1, 
       level=c(.10, .05, .01), 
       shade=c("pink", "gray55", "gray75"), ## pink -- not significant 
       legend=TRUE, back="grey90", 
       hlines=NULL, ylab="Precision (1/se)")
```


#### metacor
```{r}
# install.packages("remotes")
# remotes::install_github("guido-s/meta", ref = "develop")
url <- 'https://cran.r-project.org/src/contrib/Archive/meta/meta_4.15-0.tar.gz'
# install.packages(url, repos=NULL, type="source")
library(meta)
m.cor <- metacor(cor = Mean, 
                 n = N,
                 studlab = id,
                 data = exp_sub_mods_coef,
                 # fixed = FALSE,
                 # random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE,
                 title = "Health and Wellbeing")
summary(m.cor)
```

