---
title: "Untitled"
author: "Yingjie"
date: "`r Sys.Date()`"
output: html_document
---


# Data

```{r}

# unique(exp_sub_mods_md$Tools)

## data extracted in Table option 1 ----
exp_sub_mods_md1 <- exp_sub_mods_md %>%
  dplyr::select(1:Notes_o1)


## data extracted in Table option 2 ----
exp_sub_mods_md2 <- exp_sub_mods_md %>%
  dplyr::select(1:buffers_unit, Other_covariates_o2:Notes_o2) %>%
  
  ## check sample size data
  dplyr::select(1:n_participants, Control_N, Treatment_N, everything()) %>%
  dplyr::mutate(
    
    n_participants = str_squish(n_participants) %>% trimws(.) %>% as.numeric(.),
    Control_N   = str_squish(Control_N)   %>% trimws(.) %>% as.numeric(.),
    Treatment_N = str_squish(Treatment_N) %>% trimws(.) %>% as.numeric(.),
    
    c_n = case_when(
      !is.na(c_mean) & is.na(Control_N) & !is.na(Treatment_N) ~ Treatment_N,
      !is.na(c_mean) & is.na(Control_N) &  is.na(Treatment_N) & !is.na(n_participants) ~ n_participants,
      TRUE ~ Control_N
    ),
    
    e_n = case_when(
      !is.na(e_mean) & is.na(Treatment_N) & !is.na(Control_N) ~ Control_N,
      !is.na(e_mean) & is.na(Treatment_N) &  is.na(Control_N) & !is.na(n_participants) ~ n_participants,
      TRUE ~ Treatment_N
    ),
    
    study_label = paste(id, model_id, sep = '_')
  ) %>%

  ## convert SE, and CI to `SD`
  func_for_sd(data = .) %>%
  
  ## remove row without any data from table option 2
  dplyr::filter(!is.na(c_mean) & !is.na(e_mean) & !is.na(MH_indicator_o2)) %>%
  
  dplyr::select(1:n_participants, Control_N, c_n, Treatment_N, e_n, everything()) %>%
  as.data.frame()

##' to see the number of studies by sub_indicators
##' we might need to remove the ones with fewer case studies
unique(exp_sub_mods_md2$MH_indicator_o2) %>% sort()
exp_sub_mods_md2 %>% count(MH_indicator_o2) 

sub_indicator_selected <- c("Anger", "Anxiety", "Confusion", "Depression", "Fatigue", "Vigor", "TMD")
```





# MA - SMD

## Using `meta`
```{r}
library(meta)
library(grid)
# Use metcont to pool results.

for (sub_ind_i in sub_indicator_selected) {
  
  exp_sub_mods_md2i <- exp_sub_mods_md2 %>%
    dplyr::filter(MH_indicator_o2 == sub_ind_i)
  
  height_cm <- nrow(exp_sub_mods_md2i)
  
  ma_smd <- metacont(data = exp_sub_mods_md2i,
                     n.e = e_n,
                     n.c = c_n,
                     mean.e = e_mean,
                     mean.c = c_mean,
                     sd.e = e_sd_r,
                     sd.c = c_sd_r,
                     studlab = study_label,
                     
                     sm = "SMD",
                     method.smd = "Hedges",
                     fixed = FALSE,
                     random = TRUE,
                     method.tau = "REML",
                     hakn = TRUE,
                     title = "POMS")
  ma_smd
  

  
  #### forest ----
  f <- paste0('./figures/', 'plot_forest_POMS_', sub_ind_i, '_', today, '.png'); f
  png(filename = f, 
      # width = 3000, height = 3000, units = "px", pointsize = 22,
      width = 30, height = height_cm/1.5, units = "cm", res = 100)
  forest(ma_smd,
         # layout = "RevMan5",
         # sortvar = TE,
         # prediction = TRUE,
         addpred=TRUE, 
         print.tau2 = T,
         # lab.e = "Post-intervention",
         # lab.c = "Pre-intervention",
         # label.left = "loss",
         # label.right = "gain",
         digits.sd = 2,
         digits.tau2 = 2,
         colgap = "0.5cm",
         # colgap.forest = "1cm",
         col.by = "black",
         col.square = "black",
         col.inside = "black",
         col.square.lines = "black",
         shade=TRUE,
         # test.effect.subgroup.random = TRUE,
         pooled.totals=T,
         overall = T,
         overall.hetstat = T)
  
  # forest(ma_smd, 
  #        addpred=TRUE, 
  #        header=TRUE, 
  #        # xlim=c(-1,1), 
  #        # slab = study_label, 
  #        digits.sd = 2,
  #        digits.tau2 = 2,
  #        shade=TRUE)
  
  # Add a title to the entire plot
  grid::grid.text(label = sub_ind_i, x = 0.08, y = .98, gp=gpar(cex=2))
  
  dev.off()
  
}
```




## Using `metafor`
```{r}
library(metafor)

for (sub_ind_i in sub_indicator_selected) {
  
  exp_sub_mods_md2i <- exp_sub_mods_md2 %>%
    dplyr::filter(MH_indicator_o2 == sub_ind_i)
  
  dat1 <- metafor::escalc(
    data=exp_sub_mods_md2i,
    measure="SMD", 
    m1i=c_mean, sd1i=c_sd_r, n1i=c_n,
    m2i=e_mean, sd2i=e_sd_r, n2i=e_n)
  
  # Finally, a random-effects model can be fitted to these data with:
    
  res1 <- rma(yi, vi, data=dat1)
  res1
  
  
  
  #### auto-report using reporter() function ----
  dir.report <- paste0('./figures/'); dir.report
  metafor::reporter(res1, dir = dir.report)
  
  # reporter(res, format="pdf", 
  #          dir = paste0(dir.root, '/figures/'), 
  #          filename = 'report_metafor.PDF')
  #          
  # reporter(res, format="word")

  ### add an outlier
  # dat$yi[6] <- 2.5
  # res <- rma(yi, vi, data=dat)
  # reporter(res)
  
}
```

