---
title: "mini-review"
author: "Yingjie"
date: "2023-06-07"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
# To clear your environment
remove(list = ls())

## Load directories
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
getwd()
setwd(dirname(getwd()))

dir.raw   <- "./data/0005-covidence_export/data extraction/"
dir_share <- 'G:/Shared drives/Urban nature-health/projects/meta-analysis/figures/'

## Load common packages
source("./code/_pkgs_dirs.R")
## Additional packages
library(rprojroot)
library(tidyverse)
library(splitstackshape) ## `cSplit()`
library(Hmisc)
library(rworldmap)
today <- format(Sys.time(), "%Y%m%d"); today ## "%Y%m%d%H%M"


save_plot <- F
# save_plot <- T
```


```{r - helper data}
data(countryRegions,envir=environment(),package="rworldmap")
# str(countryRegions)

# ISO3:       ISO 3 letter country code
# ADMIN:      country name
# REGION:     7 region continent classification
# continent:  6 continents classification
```



# Data import

## Data for analysis
```{r include=FALSE}
## Choose the most updated one for formal analysis ---------------------------------------
# csv <- "review_278532_20230305161741-test mini-review-analysis.csv"
# csv <- "review_278532_20230328115335.csv"   # 2023-03-28
csv <- "review_278532_20230427120514.csv"     # 2023-04-27 
csv <- "review_278532_20230513100914.csv"     # 2023-05-13, addressed 85 consensus 

t <- basename(csv) %>% gsub('review_278532_', '', .) %>%
  str_sub(start = 1, end = 14)  %>%
  as.POSIXct(.,format="%Y%m%d%H%M%S") 
t

dd <- readr::read_csv(file = paste0(dir.raw, csv)) %>%
  dplyr::mutate(date = t) %>%
  dplyr::rename(
    'id' = 'Covidence #',
    "Country" = "Country in which the study conducted",
    "Reviewer" = "Reviewer Name",
    'Indicator' = 'Mental health indicators',
    "Tools" = "Mental health measurement tools",
    "meet_criteria" = "Does this study meet the criteria for data extraction?"
  ) %>%
  dplyr::filter(!meet_criteria %in% c('No')) %>%
  dplyr::mutate(Tools = gsub("Other: |Other:", "", Tools)) %>%
  dplyr::mutate(Country = gsub("Other: |Other:", "", Country)) %>%
  arrange(id, Reviewer) %>%
  as.data.frame()

# names(dd)


df <- dd %>%
  arrange(id, Reviewer, desc(date)) %>%
  dplyr::distinct(id, .keep_all = T) %>%
  as.data.frame()
```



# Data cleaning 

```{r - functions}
expand_col_to_long <- function(data, target_col = "Mental health indicators") {
  data_long <- data %>%
    dplyr::rename("col_split" = target_col) %>%
    ## unify the separator as ";"
    dplyr::mutate(col_split = gsub(';|,', ';', col_split)) %>%
    cSplit(
      indt = .,
      splitCols = c("col_split"),
      sep = ";",
      drop = F, # drop the original col or not
      direction = "long", # this is better than "wide"
      stripWhite = T
    ) %>% # clean white space
    dplyr::mutate(across(where(is.factor), as.character)) %>%
    dplyr::mutate(col_split = trimws(col_split)) %>%
    
    ## - convert long input in sentence format -----------------------
    # dplyr::mutate(col_split = ifelse(
    #   nchar(col_split) > 10,
    #   str_to_sentence(col_split),
    #   col_split
    # )) %>%
  
    ## - capitalizes first word but not subsequent words -------------
    dplyr::mutate(col_split = Hmisc::capitalize(col_split)) %>%
    as.data.frame() %>%
    # group_by(col_split) %>%
    # dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
    as.data.frame()

  ## change back to the original column name
  names(data_long)[names(data_long) == "col_split"] <- target_col

  return(data_long)
}



plot_freq <- function(data, var = "Mental health indicators") {
  p <- ggplot(
    data = data,
    aes(
      x = reorder(eval(parse(text = var)), n),
      y = n,
      # fill = n > 10
  )) +
  geom_col(show.legend = F) +
  theme_bw() +
  # theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  coord_flip() +
  # scale_fill_distiller(name = '', palette = "Blues", guide = "colorbar", direction = 1) +
  xlab("")
  
  return(p)
}


func_ggsave <- function(fname, w = 7, h = 4, save_png = save_plot) {
  if (save_png == T) {
    ggsave(filename = fname, plot = last_plot(), width = w, height = h, units = "in", dpi = 300)
  } else {
    print('The plot will not be saved.')
  }
}

```



## Indicator
```{r - indicator, include=FALSE}
## keep columns of interest, and clean data

func_clean_indicators <-  function(data) {
  d <- data %>%
    dplyr::mutate(
    Indicator = str_squish(Indicator),
    Indicator = gsub("Other\\: |in general\\*", "", Indicator),
    Indicator = gsub("\\(include schizophrenia\\)", "", Indicator),
    Indicator = gsub("\\s*\\([^\\)]+\\)", "", Indicator), # remove text within parenthesis 
    Indicator = gsub("\\/Restorativeness", "", Indicator),
    Indicator = gsub("Restoration experience|Restorative experience|Restorativeness", 
                     "Restorative effects", Indicator, ignore.case = T), 
    Indicator = gsub("Attention capacity|Sustained attention", "Attention", Indicator, ignore.case = T), ##  
    Indicator = gsub("Behavioural", "Behavioral", Indicator, ignore.case = T), ##  
    Indicator = gsub("Behavioral problems", "Behavioral disorder", Indicator, ignore.case = T), ## 
    Indicator = gsub("Burnout symptom", "Burnout", Indicator, ignore.case = T),
    Indicator = gsub("Burnout fatigue|burnout fatigue", "Burnout", Indicator, ignore.case = T),
    Indicator = gsub("Cognitions and Conduct", "Cognitive functioning", Indicator, ignore.case = T), # 
    Indicator = gsub("Quality of life|Quality of Life", "Quality of life;", Indicator),# 
    Indicator = gsub("Psychological distress|psychological distress", "Mental distress", Indicator),# # 
    Indicator = gsub("Symptoms of psychosis", "Psychosis", Indicator, ignore.case = T), #### 

    Indicator = gsub(",", ";", Indicator),
    Indicator = trimws(Indicator)
    ) %>%
    as.data.frame()
  
  return(d)
}



dt <- df %>%
  dplyr::select(1:4, matches("Country|Mental health|Indicator|Tools")) %>%
  dplyr::select(!matches("duration", ignore.case = T)) %>%
  func_clean_indicators(data = .) %>%
  dplyr::arrange(!is.na(Indicator), Reviewer) %>%
  as.data.frame()




# names(dt)


## stat
## - by indicator
dt.ind <- dt %>%
  dplyr::filter(str_detect(string = Indicator, pattern = "exclude", negate = T)) %>%
  group_by(Indicator, Tools, Country) %>%
  dplyr::count() %>%
  ungroup() %>%
  as.data.frame()


## - clean and format
dt.ind.cl <- dt.ind %>% 
  expand_col_to_long(data = ., target_col = "Indicator") %>%
  dplyr::mutate(
    Indicator = gsub("emotions|Emotions", "Emotion", Indicator),
    Indicator = gsub(";", "", Indicator),
    ) %>%
  dplyr::filter(!Indicator %in% c('', NA)) %>%
  dplyr::filter(!Tools %in% c('', NA)) %>%
  as.data.frame()

dt.ind.clean <- dt.ind.cl %>% 
  group_by(Indicator) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  as.data.frame()

```


```{r - indicator bar}
dt.ind.clean %>%
  dplyr::slice_max(order_by = n, n = 20) %>%
  ggplot(aes(
    x = reorder(Indicator, n),
    y = n,
    # fill = n
  )) +
  geom_col() +
  coord_flip() +
  # scale_fill_distiller(name = '', palette = "Blues", guide = "colorbar", direction = 1) +
  xlab("") +
  ggtitle("Frequency of Mental health indicators") +
  theme_bw() +
  theme(
    # axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
    plot.title = element_text(size = 10, hjust = 1.2, face = 'bold')
    )

f <- "mini-review_indicators.png"
fname <- paste0(dir.fig, f)
w = 3
h = 5
func_ggsave(fname = fname, w = w, h = h)

fname <- paste0(dir_share, f); fname
func_ggsave(fname = fname, w = w, h = h)
```


```{r - indicators selected for MA, include=FALSE}

dt.ind.expand <- dt %>% 
  dplyr::select(1:6, Tools, -Title) %>%
  expand_col_to_long(data = ., target_col = "Indicator") %>%
  as.data.frame()


## select the most used indicators in lit for meta-analysis
indicator_selected <- c('Mental health', 'Mental wellbeing')


dt.ind.selected <- dt.ind.expand %>% 
  dplyr::filter(Indicator %in% indicator_selected) %>%
  arrange(Tools, id) %>%
  dplyr::mutate(id = paste0('#', id)) %>%
  as.data.frame()

f <- paste0('./data/0301-MA-input/', 'paperID_byTopIndicators.CSV')
readr::write_csv(x = dt.ind.selected, file = f)
```

