---
title: "Untitled"
author: "Yingjie"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

today <- format(Sys.time(), "%Y%m%d"); today ## "%Y%m%d%H%M"
vv = ""
```

## data

```{r}

library(readr)
library(dplyr)
library(stringr)

f <- './data/YY/meta_tool_type.CSV'
d <- readr::read_csv(f, show_col_types = FALSE) %>%
  dplyr::select(-subgroup) %>%
  ## use the names based on my function 
  dplyr::rename('tool' = 'MH_tool', 
                'subgroup' = 'ind_sub') %>%
  ## some columns are missing in your data
  dplyr::mutate(group_name = 'nature_type',
                ind_sub = tool) %>%
  ## change the nature type names based on my classification 
  ## in this way, you will be able to use the pre-set color from my function 
  dplyr::mutate(
    subgroup = case_when(
      subgroup == "Tree" ~ "Greenspace - Forest", 
      subgroup == "General" ~ 'Greenspace',
      subgroup == "Blue" ~ 'Bluespace',
      subgroup == "Park" ~ "Greenspace - Park",
      subgroup == "Grass" ~ "Greenspace - Grassland",
      T ~ 'Others'
      
    )
  ) %>%
  dplyr::select(tool,        ## on the header of each subplot
                ind_sub,     ## you do not have sub-indicators, so this is useless but you still need this column following my function 
                group_name,  ## the group name for your subgroups
                subgroup,    ## the subgroups - as shown as multiple lines in each subplot
                everything())
  


f <- './data/YY/meta_metric_type.CSV'
d2 <- readr::read_csv(f, show_col_types = FALSE) %>%
  dplyr::select(-subgroup) %>%
  ## format data based on my function
  dplyr::rename('subgroup' = 'ind_sub') %>%
  
  ## format data based on my function 
  dplyr::mutate(
    tool = type_nature#,
  ) %>%
  dplyr::mutate(group_name = 'nature_quantity',
                ind_sub = tool) %>%
  dplyr::select(-type_nature) %>%
  dplyr::select(tool, ind_sub, group_name, subgroup, everything()) #%>%


ma_result_all <- rbind(d, d2)

unique(d$subgroup)

```


#### - plot
```{r}
source('./code/func_plot_ma.R')
source('./code/func_color_bygroup.R')


subgroups <- c(
  'nature_type',
  'nature_quantity')

ind_sub_levels = unique(ma_result_all$ind_sub)
facet_ncol = 4
dir.fig <- "./data/YY/"


## indicators to be included in the combined sub-group analysis plots
unique(ma_result_all$tool) %>% sort()
unique(ma_result_all$ind_sub) %>% sort()


##' @Yuanyuan: you no need to change scripts below, 
##' but you need to format your data as required by my functions
##' see what I did in the previous chunck 

for (subgroup_select in subgroups) {
  
  ## subset data
  ma_result_all_sub <- ma_result_all %>%
    dplyr::filter(subgroup != 'Overall', 
                  group_name == subgroup_select)
  
  ## postfix to be added to figure names
  postfix_group <- paste0("_subgroup_", subgroup_select); postfix_group
  
  ##' decide color scheme 
  if(subgroup_select == 'nature_type'){
    group_title = str_to_sentence(gsub('_|_o2', ' ', subgroup_select)) %>% trimws()
    color_bygroup = nature_type_color; 
    group_list = nature_type_list
  } else if(subgroup_select == 'age_group'){
    group_title = str_to_sentence(gsub('_', ' ', subgroup_select))
    color_bygroup = age_group_color; 
    group_list = age_group_list
  } else if(subgroup_select == 'gender_group'){
    group_title = str_to_sentence(gsub('_', ' ', subgroup_select))
    color_bygroup = gender_group_color; 
    group_list = gender_group_list
  } else if(subgroup_select == 'duration_group'){
    group_title = 'Duration in nature'
    color_bygroup = duration_group_color; 
    group_list = duration_group_list
  } else if(subgroup_select == 'Region'){
    group_title = subgroup_select
    color_bygroup = region_color; 
    group_list = region_list
  } else {
    # next
    group_title = str_to_sentence(gsub('_|_o2', ' ', subgroup_select)) %>% trimws()
    group_list = unique(ma_result_all_sub$subgroup) %>% sort()
    color_bygroup = func_color_bygroup(df = ma_result_all_sub, column_name = 'subgroup')
  }
  

  
  
  ##' run sourced code 
  ##' 
  ##' 1. plot by tool and combine plots
  # source('./code/020s1_subgroup_loop_source_code.R')
  
  ##' 2. pool all tools together and plot
  source('./code/020s2_subgroup_loop_source_code.R')
  
}


```